CREATE DATABASE GIAOVIEN

USE GIAOVIEN
GO

CREATE TABLE CONNECTDB(
	TENMAY VARCHAR(50),
	TENCSDL VARCHAR(50),
	USERDB VARCHAR(50),
	PASSWORDB VARCHAR(50),
);

CREATE TABLE COSO(
	MACOSO NVARCHAR(50),
	TENCOSO NVARCHAR(50),
	CONSTRAINT PK_COSO PRIMARY KEY (MACOSO)
);

CREATE TABLE DONVI 
(	MADONVI NVARCHAR(10) NOT NULL,
	TENDONVI NVARCHAR(50) NOT NULL,
	MACOSO NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_DONVI PRIMARY KEY (MADONVI),
	CONSTRAINT FK_COSO_DONVI FOREIGN KEY (MACOSO) REFERENCES COSO(MACOSO)
);

